Issue-449: Rollback fails in case of only 1 Segment Store Pod
pravega/pravega-operator pull request #450
Opened 2020-09-14 17:14 UTC by Prabhaker24

Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>

### Change log description
Rollback fails in case of only 1 Segment Store Pod

### Purpose of the change
Fixes #449 

### What the code does
This code changes the order of rollback in case of 1 ss i.e first the ss get's rollback then the controller which ensures readiness check doesn't fail and the rollback is successful.

### How to verify it
Deploy pravega with 1 ss pod and try and upgrade and fail the upgrade process then rollback the cluster and first ss should get rollback then the controller.

2020-09-16 05:48 UTC, anishakj requested changes

2020-09-16 05:48 UTC, anishakj commented on pkg/controller/pravegacluster/upgrade_test.go
> +				It("should set rollback condition reason to UpdatingSegmentStore and message to 0", func() {
Could you please add a test case for rollback with more than one segment store replicas.

2020-09-17 06:58 UTC, anishakj approved these changes
LGTM

2020-09-17 09:08 UTC, SrishT approved these changes
LGTM

2020-09-17 09:12 UTC, merged