Extend functionality of Test Mode to enable privileged mode for Segme…
pravega/pravega-operator pull request #508
Opened 2021-02-16 11:12 UTC by leapsky

Extend functionality of Test Mode to enable `privileged mode` for Segment Store containers #507

### Change log description

* Added `SecurityContext` definition in Segment Store containers' description

### Purpose of the change

This functionally will allow us to use Linux tracing tools without patching Pravega Operator and make profiling more simple.

### What the code does

Enable privileged mode for Segment Store containers.

### How to verify it

When Pravega deployment is completed, check if Segment Store containers running in privileged mode:
`kubectl get pod pravega-pravega-segment-store-0 -o yaml | grep privileged`

2021-02-19 06:17 UTC, anishakj requested changes
We are setting security context for the pod at  https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravega/pravega_segmentstore.go#L169. Can't we set the `privileged` mode there?

2021-02-21 20:49 UTC, leapsky commented
We could use, but in `segmentStoreSecurityContext`, there is no `privileged` among the described properties.

https://github.com/pravega/pravega-operator/blob/master/deploy/crds/pravega.pravega.io_pravegaclusters_crd.yaml#L1835

2021-02-22 08:22 UTC, anishakj commented
> We could use, but in `segmentStoreSecurityContext`, there is no `privileged` among the described properties.
> 
> https://github.com/pravega/pravega-operator/blob/master/deploy/crds/pravega.pravega.io_pravegaclusters_crd.yaml#L1835

Got it, both of the security context structures are different. Could you fix the formatting errors

2021-02-22 19:07 UTC, leapsky commented
Sure, will do.

2021-03-03 11:38 UTC, anishakj approved these changes
LGTM

2021-03-03 11:39 UTC, merged