Issue 489: Added support for custom storage option in long term storage
pravega/pravega-operator pull request #585
Opened 2021-10-20 12:48 UTC by anishakj

Signed-off-by: anishakj <anisha.kj@dell.com>

### Change log description

Adding a new field for custom storage in longtermstoragespec
### Purpose of the change

 Fixes #489

### What the code does

Currently, operator supports HDFS, ECS and filesystem as longtermstorage options, added support for custom storage so that users can provide required options and env variables based on the storage type selected.

We can also pass env varaibles via `segmentStoreEnvVars`. But  in case,if we do not set `longtermstorage` type, it can cause conflicts

### How to verify it

Example of helm charts with `s3` as custom storage

```
storage:
  longtermStorage:
    type: custom
    custom:
      options:
        pravegaservice.storage.layout: "CHUNKED_STORAGE"
        pravegaservice.storage.impl.name: "S3"
        s3.bucket: bucketname
        s3.prefix: "10-11-1"
        s3.connect.config.uri.override: "false"
        s3.connect.config.uri: uri
        s3.connect.config.access.key: keyname
        s3.connect.config.secret.key: keyvalue
      env:
        TIER2_STORAGE: "S3"
        AWS_ACCESS_KEY_ID: "key"
        AWS_SECRET_ACCESS_KEY: "secret"
```

Verified that able to install pravega with `S3` as custom storage, also ran system tests

2021-10-21 11:27 UTC, nishant-yt reviewed
Requested changes

2021-10-21 12:30 UTC, jkhalack commented on pkg/apis/pravega/v1beta1/pravega.go
> +	Options map[string]string `json:"options"`
@anishakj @nishant-yt Is there a use case when **only one** of `options`,`env` blocks would have to be supplied?

2021-10-21 16:53 UTC, anishakj commented
> > > @anishakj Could you add some (commented out) example on how this issue might be used to the helm chart (https://github.com/pravega/pravega-operator/blob/master/charts/pravega/values.yaml#L107), please?
> > 
> > 
> > have to create separate PR for that in Pravega/charts repo. Charts repo here is deprecated
> 
> Would you at least add it to the PR description?

Values need to be used in helm chart are added in PR description.

2021-10-21 17:16 UTC, jkhalack approved these changes

2021-10-22 12:22 UTC, jkhalack requested changes

2021-10-25 12:07 UTC, jkhalack approved these changes
LGTM

2021-10-25 12:38 UTC, SrishT requested changes

2021-10-25 12:53 UTC, SrishT approved these changes
LGTM

2021-10-25 15:17 UTC, nishant-yt approved these changes
LGTM

2021-10-25 15:49 UTC, merged